import virtualmachine.Sistema;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {

    public static void main(String[] args) {
        Sistema.main(args);
    }

    public void bootstrap() {
        // Load each program one at a time while each program is connected to the next   
        // Load drivers
    }
}
