import virtualmachine.Sistema;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {
    public String getGreeting() {
        return "Program Initializing!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Sistema.main(args);
    }

    public void bootstrap() {
        // Load each program one at a time while each program is connected to the next   
        // Load drivers
    }
}
